name: Publish

concurrency:
  group: publish
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA, tag, or branch to checkout (leave blank for default)'
        required: false
        type: string
  # schedule:
   # - cron: '0 10 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fail if we are attempting to run on the master branch without a custom commit
      if: ${{ github.ref_name == 'master' && github.repository == 'space-wizards/space-station-14' && inputs.commit_sha == '' }}
      run: exit 1

    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        # Check out the input SHA if provided; otherwise, fall back to the selected branch
        ref: ${{ inputs.commit_sha || github.ref }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --hybrid-acz

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Upload Artifacts to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: "Release-v${{ github.run_number }}"
        path: release/
        if-no-files-found: error
